"""templates_v2 / atom_oracle.py — SEMANTIC oracle for generated lints.

The pipeline's only existing semantic gate is a single-vote LLM judge
(`binary_verdict == EXPRESSES`), which is unsound — it rubber-stamps
over-strict lints (e.g. a conditional rule whose precondition was dropped,
producing an unconditional lint that fires on valid certs).

This module replaces that judge for the deterministic IR->code path with a
DETERMINISTIC, cert-based oracle. It has two independent parts:

  (a) Over-strictness sentinel  [sentinel()]
      Run a generated lint over a corpus of real, broadly-valid certs.
      A faithful lint should rarely fire Error on valid certs; one that fires
      on a large fraction is almost certainly over-strict (dropped precondition
      / unconditional encoding of a conditional rule). NO hand-built fixtures,
      NO per-rule logic — purely the cert corpus + the rendered Go.

  (b) Per-atom faithfulness     [certify_atoms()]  (built incrementally)
      For each DSL atom, a satisfying cert (predicate TRUE) must yield Pass and
      a violating cert (predicate FALSE) must yield the Error severity, per the
      tree_codegen body contract `if {expr} { Pass } else { Error }`. Atoms that
      pass are CERTIFIED; an IR tree built only from certified atoms is then
      synonymy-guaranteed (code == IR) by structural composition. Fixtures are
      per-atom-class, parameterized over vocab — never keyed to a rule_id.

Shared core: a Go driver (generated by `_driver_src`) that imports the lint
packages, parses each PEM with zcrypto/x509, runs CheckApplies+Execute, and
prints one JSON record {lint, cert, status} per (lint, cert). Reuses
runner.build_workspace / write_lint / MODNAME for the scratch zlint+zcrypto
module.
"""
from __future__ import annotations

import json
import re
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional

from . import runner

ROOT = Path(__file__).resolve().parent.parent.parent
REAL_CERTS = ROOT / "experiments/results/cert_cache/pem_samples"   # 100 real CT certs
ZLINT_TESTDATA = ROOT / "cicas_backend/zlint/v3/testdata"           # 1325 named certs


@dataclass
class LintUnderTest:
    rule_id: int
    code: str               # full generated .go file content
    pkg: str                # e.g. cicasgen_aia_not_critical_3899 (== package == dir)
    struct: str             # e.g. CicasGen3899
    ctor: str               # e.g. NewCicasGen3899


_PKG_RE  = re.compile(r"^\s*package\s+(\w+)", re.M)
_CTOR_RE = re.compile(r"func\s+(New\w+)\s*\(")


def lint_from_code(rule_id, code: str) -> LintUnderTest:
    """Build a LintUnderTest from generated Go. The package name is descriptive
    (cicasgen_<slug>_<rule_id>) and no longer reconstructable from rule_id, so
    PARSE the actual `package` and `New…` constructor out of the code. Falls
    back to the legacy rule_id-only names if the code can't be parsed (keeps
    older stored `generated_code` records working)."""
    m_pkg, m_ctor = _PKG_RE.search(code or ""), _CTOR_RE.search(code or "")
    if m_pkg and m_ctor:
        pkg = m_pkg.group(1)
        ctor = m_ctor.group(1)
        return LintUnderTest(int(rule_id), code, pkg, ctor[3:], ctor)
    pkg = f"cicasgen_{int(rule_id):04d}"
    struct = f"CicasGen{int(rule_id):04d}"
    return LintUnderTest(int(rule_id), code, pkg, struct, f"New{struct}")


# --------------------------------------------------------------------------
# Go driver: import all lint packages, run each over each cert, emit JSONL.
# --------------------------------------------------------------------------

_DRIVER_HEAD = '''\
// Code generated by atom_oracle.py — runs generated lints over a cert corpus.
package main

import (
\t"encoding/json"
\t"encoding/pem"
\t"os"
\t"path/filepath"
\t"strings"

\t"github.com/zmap/zcrypto/x509"
\t"github.com/zmap/zlint/v3/lint"
{lint_imports}
)

var lints = map[string]lint.LintInterface{{
{lint_entries}
}}

func runOne(l lint.LintInterface, cert *x509.Certificate) (status string) {{
\tdefer func() {{
\t\tif r := recover(); r != nil {{
\t\t\tstatus = "PANIC"
\t\t}}
\t}}()
\tif !l.CheckApplies(cert) {{
\t\treturn "NA"
\t}}
\tres := l.Execute(cert)
\tif res == nil {{
\t\treturn "NIL"
\t}}
\treturn res.Status.String()
}}

func main() {{
\tcertDir := os.Args[1]
\tfiles, _ := filepath.Glob(filepath.Join(certDir, "*.pem"))
\tenc := json.NewEncoder(os.Stdout)
\tfor _, f := range files {{
\t\tcertName := filepath.Base(f)
\t\tdata, err := os.ReadFile(f)
\t\tif err != nil {{
\t\t\tcontinue
\t\t}}
\t\tder := data
\t\tif strings.Contains(string(data), "-BEGIN CERTIFICATE-") {{
\t\t\tblock, _ := pem.Decode(data)
\t\t\tif block == nil {{
\t\t\t\tcontinue
\t\t\t}}
\t\t\tder = block.Bytes
\t\t}}
\t\tcert, err := x509.ParseCertificate(der)
\t\tif err != nil {{
\t\t\t_ = enc.Encode(map[string]string{{"cert": certName, "parse_error": err.Error()}})
\t\t\tcontinue
\t\t}}
\t\tfor name, l := range lints {{
\t\t\t_ = enc.Encode(map[string]string{{"lint": name, "cert": certName, "status": runOne(l, cert)}})
\t\t}}
\t}}
}}
'''


def _driver_src(luts: list[LintUnderTest]) -> str:
    imports = "\n".join(
        f'\tp{l.rule_id} "{runner.MODNAME}/pkgs/{l.pkg}"' for l in luts)
    entries = "\n".join(
        f'\t"{l.pkg}": p{l.rule_id}.{l.ctor}(),' for l in luts)
    return _DRIVER_HEAD.format(lint_imports=imports, lint_entries=entries)


def run_lints_over_certs(luts: list[LintUnderTest], cert_dir: Path,
                         workspace: Optional[Path] = None,
                         timeout: int = 600) -> dict:
    """Build a workspace with every lint, run the driver over cert_dir.
    Returns {lint_pkg: {cert_name: status}} plus a '_parse_errors' list."""
    if not luts:
        return {}
    own_ws = workspace is None
    tmp = tempfile.mkdtemp(prefix="cicas_oracle_") if own_ws else None
    ws = Path(tmp) if own_ws else workspace
    try:
        runner.build_workspace(ws)
        for l in luts:
            rl = runner.RenderedLint(
                rule_id=l.rule_id, pkg=l.pkg, struct_name=l.struct,
                file_content=l.code, imports=set(), statement="",
                template_id="<oracle>", slots={})
            runner.write_lint(ws, rl)
        # build_workspace writes a stub main.go with its own func main(); overwrite
        # it (two func main() in one package would not compile).
        (ws / "main.go").write_text(_driver_src(luts))
        proc = subprocess.run(
            ["go", "run", ".", str(cert_dir)],
            cwd=ws, capture_output=True, text=True, timeout=timeout)
        if proc.returncode != 0:
            raise RuntimeError(f"oracle driver failed:\n{proc.stderr[:2000]}")
        results: dict = {}
        parse_errors: list = []
        for line in proc.stdout.splitlines():
            if not line.strip():
                continue
            rec = json.loads(line)
            if "parse_error" in rec:
                parse_errors.append((rec["cert"], rec["parse_error"]))
                continue
            results.setdefault(rec["lint"], {})[rec["cert"]] = rec["status"]
        results["_parse_errors"] = parse_errors
        return results
    finally:
        if own_ws and tmp:
            import shutil
            shutil.rmtree(tmp, ignore_errors=True)


# --------------------------------------------------------------------------
# (a) Over-strictness sentinel
# --------------------------------------------------------------------------

def sentinel(luts: list[LintUnderTest], cert_dir: Path = REAL_CERTS,
             flag_frac: float = 0.30) -> dict:
    """Run each lint over a corpus of broadly-valid real certs and report the
    fraction of certs on which it fires Error/Warn. Lints firing above
    flag_frac are flagged as likely over-strict (the dropped-precondition
    class). Returns {pkg: {error_frac, n_error, n_total, flagged}}."""
    res = run_lints_over_certs(luts, cert_dir)
    pe = res.pop("_parse_errors", [])
    report = {}
    for l in luts:
        statuses = res.get(l.pkg, {})
        n = len(statuses)
        # zlint Status.String() is lowercase for severities ("error"/"warn"/
        # "notice"/"pass"/"fatal") but uppercase "NA"/"NE". Normalize.
        norm = {k: v.lower() for k, v in statuses.items()}
        n_err = sum(1 for s in norm.values() if s in ("error", "warn"))
        n_na = sum(1 for s in norm.values() if s == "na")
        n_panic = sum(1 for s in norm.values() if s == "panic")
        frac = (n_err / n) if n else 0.0
        report[l.pkg] = {
            "rule_id": l.rule_id, "n_total": n, "n_error": n_err,
            "n_na": n_na, "n_panic": n_panic,
            "error_frac": round(frac, 3),
            "flagged_overstrict": frac >= flag_frac,
        }
    report["_parse_errors"] = len(pe)
    return report


# --------------------------------------------------------------------------
# CLI: sentinel over the currently-accepted lints (det + llm EXPRESSES)
# --------------------------------------------------------------------------

def _load_accepted() -> list[LintUnderTest]:
    R = ROOT / "experiments/results"
    det = [json.loads(x) for x in open(R / "exp_codegen_det_v2.jsonl") if x.strip()]
    llm = [json.loads(x) for x in open(R / "exp_codegen_llm_v2.jsonl") if x.strip()]
    luts = []
    seen = set()
    for r in det:
        if r.get("status") == "deterministic" and r.get("compile_status") == "pass" and r.get("generated_code"):
            luts.append(lint_from_code(r["rule_id"], r["generated_code"])); seen.add(str(r["rule_id"]))
    for r in llm:
        rid = str(r["rule_id"])
        if rid in seen:
            continue
        if r.get("binary_verdict") == "EXPRESSES" and r.get("compile_status") == "pass" and r.get("generated_code"):
            luts.append(lint_from_code(r["rule_id"], r["generated_code"]))
    return luts


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--flag-frac", type=float, default=0.30)
    ap.add_argument("--limit", type=int, default=0, help="0 = all accepted lints")
    a = ap.parse_args()
    luts = _load_accepted()
    if a.limit:
        luts = luts[:a.limit]
    print(f"sentinel: running {len(luts)} accepted lints over {REAL_CERTS.name} "
          f"({len(list(REAL_CERTS.glob('*.pem')))} real certs)\n")
    rep = sentinel(luts, flag_frac=a.flag_frac)
    pe = rep.pop("_parse_errors", 0)
    flagged = sorted((v for v in rep.values() if v["flagged_overstrict"]),
                     key=lambda v: -v["error_frac"])
    print(f"parse errors: {pe}")
    print(f"FLAGGED over-strict (fires on >= {a.flag_frac:.0%} of valid certs): "
          f"{len(flagged)} / {len(luts)}\n")
    for v in flagged:
        print(f"  R{v['rule_id']:<6} fires Error on {v['n_error']:>3}/{v['n_total']:<3} "
              f"({v['error_frac']:.0%})  na={v['n_na']} panic={v['n_panic']}")
    # spotlight the known-bad trio from the audit
    print("\n  [known-bad audit] 23890/23897/23991:")
    for rid in ("23890", "23897", "23991"):
        v = next((x for x in rep.values() if str(x["rule_id"]) == rid), None)
        if v:
            print(f"    R{rid}: Error on {v['n_error']}/{v['n_total']} "
                  f"({v['error_frac']:.0%})  flagged={v['flagged_overstrict']}")


if __name__ == "__main__":
    main()
