"""codegen/intree_emitter.py — emit a generated lint INTO the real zlint tree.

The runner.py templates render a generated lint into a THROWAWAY workspace whose
package name is `cicasgen_<slug>_<rule_id>` — that is only for the `go build`
compile gate and never lands in the shipped linter. To actually test certificates
with our generated lints, the file must live inside the real zlint source tree:

  RFC 5280 rules      -> zlint/v3/lints/rfc/        (package rfc)
  CABF-BR rules       -> zlint/v3/lints/cabf_br/    (package cabf_br)

A file under lints/rfc/ MUST declare `package rfc` (Go requires one package per
directory), so we CANNOT reuse the cicasgen_<...> package name there. Instead the
attribution is carried by the lint **Name** field: every generated lint is named
`cicasgen_<slug>_<rule_id>`. zlint's own lints use e_/w_/n_ severity prefixes and
never start with `cicasgen_`, so the prefix cleanly partitions "ours" from the
upstream lints in any zlint output (see results_attribution.py).

Struct names are `CicasGen<rule_id>` (Go-unique within the package); the registered
Name doubles as the attribution key and is recorded in the emission manifest.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

from . import tree_codegen, render
from .det_codegen import severity_from_obligation
from .tree_to_natural import tree_slug


# package directory per source. Anything else is rejected — we only ship into
# dirs that already exist in the upstream tree so `go build ./...` keeps working.
_SOURCE_TO_PKG = {
    "RFC": ("rfc", "RFC5280"),
    "RFC5280": ("rfc", "RFC5280"),
    "CABF": ("cabf_br", "CABFBaselineRequirements"),
    "CABF-BR": ("cabf_br", "CABFBaselineRequirements"),
    "CABF_BR": ("cabf_br", "CABFBaselineRequirements"),
}


_INTREE_FILE_TEMPLATE = '''\
// Code generated by CICAS rule-codegen — DO NOT EDIT.
// NOT a zlint-authored lint. Auto-generated from {source} {section} (rule {rule_id}).
// The lint Name is prefixed `cicasgen_` so it can never be mistaken for or
// counted as upstream zlint coverage. See codegen/results_attribution.py.

package {pkg}

import (
{imports}
)

func init() {{
\tlint.RegisterCertificateLint(&lint.CertificateLint{{
\t\tLintMetadata: lint.LintMetadata{{
\t\t\tName:        {name_lit},
\t\t\tDescription: {desc_lit},
\t\t\tCitation:    {citation_lit},
\t\t\tSource:      lint.{source_const},
\t\t}},
\t\tLint: New{struct_name},
\t}})
}}

type {struct_name} struct{{}}

func New{struct_name}() lint.LintInterface {{
\treturn &{struct_name}{{}}
}}

func (l *{struct_name}) CheckApplies(c *x509.Certificate) bool {{
\treturn {check_applies_expr}
}}

func (l *{struct_name}) Execute(c *x509.Certificate) *lint.LintResult {{
{execute_body}
}}
'''


def _go_string(s: str) -> str:
    out = '"'
    for ch in s or "":
        if ch == "\\":   out += "\\\\"
        elif ch == '"':  out += '\\"'
        elif ch == "\n": out += "\\n"
        elif ch == "\r": out += "\\r"
        elif ch == "\t": out += "\\t"
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            out += f"\\u{ord(ch):04x}"
        else:
            out += ch
    return out + '"'


def _build_imports(imps: set) -> str:
    stdlib = sorted(i for i in imps if "/" not in i
                    or i.startswith(("math", "regexp", "time", "fmt")))
    external = sorted(i for i in imps if i not in stdlib)
    lines = [f'\t"{i}"' for i in stdlib]
    if external and stdlib:
        lines.append("")
    lines += [f'\t"{i}"' for i in external]
    return "\n".join(lines)


def lint_name_for(rule_id: int, tree=None) -> str:
    """The registered lint Name (= attribution key). cicasgen_<slug>_<rule_id>,
    or cicasgen_<rule_id> when no descriptive slug can be derived."""
    slug = ""
    if tree is not None:
        try:
            slug = tree_slug(tree)
        except Exception:
            slug = ""
    name = f"cicasgen_{slug}_{int(rule_id)}" if slug else f"cicasgen_{int(rule_id)}"
    name = re.sub(r"[^a-z0-9_]", "_", name.lower())
    return re.sub(r"_+", "_", name).strip("_")


def resolve_package(source: str) -> tuple[str, str]:
    """(package_dir, Source const) for a rule source. Raises ValueError on an
    unsupported source so we never write into a directory zlint doesn't have."""
    key = (source or "").upper().replace(" ", "").replace("-", "_")
    # normalize a few spellings
    if key in _SOURCE_TO_PKG:
        return _SOURCE_TO_PKG[key]
    if "RFC" in key or "5280" in key:
        return _SOURCE_TO_PKG["RFC"]
    if "CABF" in key or "BR" in key:
        return _SOURCE_TO_PKG["CABF-BR"]
    raise ValueError(f"unsupported rule source for in-tree emission: {source!r}")


# Map a CABF certificate-profile to its zlint scope predicate. The CABF BR
# §7.1.2 sub-tree is partitioned by certificate type; a lint authored for one
# profile MUST NOT fire on certificates of another profile (that was the bug
# behind ~all the earlier false positives — every lint ran on every cert).
#
# Scope is derived from the rule's CABF section number (authoritative divisor)
# with the human title as a secondary signal. We only ever *narrow* scope: when
# the profile cannot be determined unambiguously we fall back to `true` (the old
# behavior), so this change can remove false positives but never add them.
#
# §7.1.2.1   Root CA                 -> IsRootCA
# §7.1.2.2   Cross-Cert'd Sub CA     -> IsSubCA
# §7.1.2.3   Internal/Sub CA         -> IsSubCA
# §7.1.2.4/5 Technically-Constrained -> IsSubCA
# §7.1.2.6   Subscriber              -> IsSubscriberCert
# §7.1.2.7   Subscriber              -> IsSubscriberCert
# §7.1.2.8   OCSP Responder          -> IsDelegatedOCSPResponderCert
# §7.1.2.10  CA Certificate (common) -> IsCACert
# §7.1.2.11  Common to all CAs       -> IsCACert
_SCOPE_BY_TITLE = (
    ("ocsp responder", "util.IsDelegatedOCSPResponderCert(c)"),
    ("root ca", "util.IsRootCA(c)"),
    ("cross-certified subordinate", "util.IsSubCA(c)"),
    ("subordinate ca", "util.IsSubCA(c)"),
    ("technically constrained", "util.IsSubCA(c)"),
    ("subscriber", "util.IsSubscriberCert(c)"),
    ("organization validated", "util.IsSubscriberCert(c)"),
    ("individual validated", "util.IsSubscriberCert(c)"),
    ("domain validated", "util.IsSubscriberCert(c)"),
    ("extended validation", "util.IsSubscriberCert(c)"),
    ("ca certificate", "util.IsCACert(c)"),
)


def _section_scope(section: str) -> Optional[str]:
    """Profile predicate implied by a CABF §7.1.2.x section number, or None.

    §7.1.2.7 (Subscriber) is further partitioned by *validation tier*; a rule
    under the OV/IV/EV tier must NOT fire on a DV cert (which has no org/locality
    requirements). zlint scopes these via the Reserved Policy OID the cert
    carries (see e_cert_policy_ov_requires_province_or_locality), so we do the
    same: gate on IsSubscriberCert AND the tier's BR policy OID.

        §7.1.2.7    common subscriber      -> IsSubscriberCert
        §7.1.2.7.1  common subscriber      -> IsSubscriberCert
        §7.1.2.7.2  Domain Validated       -> IsSubscriberCert + DV OID
        §7.1.2.7.3  Individual Validated    -> IsSubscriberCert + IV OID
        §7.1.2.7.4  Organization Validated  -> IsSubscriberCert + OV OID
        §7.1.2.7.5  Extended Validation     -> IsSubscriberCert + EV
    """
    s = (section or "").strip()
    # normalize to dotted components: "7.1.2.8.4" -> ["7","1","2","8","4"]
    parts = s.split(".")
    if len(parts) < 4 or parts[:3] != ["7", "1", "2"]:
        return None
    try:
        profile = int(parts[3])
    except ValueError:
        return None
    # Subscriber validation-tier sub-profiles (§7.1.2.7.x)
    if profile == 7 and len(parts) >= 5:
        tier = parts[4]
        tier_oid = {
            "2": "util.BRDomainValidatedOID",
            "3": "util.BRIndividualValidatedOID",
            "4": "util.BROrganizationValidatedOID",
            "5": "util.BRExtendedValidatedOID",
        }.get(tier)
        if tier_oid:
            return (f"util.IsSubscriberCert(c) && "
                    f"util.SliceContainsOID(c.PolicyIdentifiers, {tier_oid})")
        # .1 (common) or anything else under .7 -> all subscriber certs
        return "util.IsSubscriberCert(c)"
    return {
        1: "util.IsRootCA(c)",
        2: "util.IsSubCA(c)",
        3: "util.IsSubCA(c)",
        4: "util.IsSubCA(c)",
        5: "util.IsSubCA(c)",
        6: "util.IsSubscriberCert(c)",
        7: "util.IsSubscriberCert(c)",
        8: "util.IsDelegatedOCSPResponderCert(c)",
        10: "util.IsCACert(c)",
        11: "util.IsCACert(c)",
    }.get(profile)


# A "the AKI keyIdentifier MUST be present" obligation does NOT apply to a
# self-signed certificate: a self-signed cert has no separate issuing key to
# identify, so RFC 5280 §4.2.1.1 makes the AKI optional for it and the CABF Root
# CA profile inherits that relaxation. zlint encodes the same carve-out in
# authorityKeyIdNoKeyIdField (Pass when IsCACert && IsSelfSigned). We therefore
# narrow the scope of a presence-of-AKI-keyIdentifier lint to exclude self-signed
# certs. This is a NARROWING (removes false positives, never adds), keyed on the
# IR subject + obligation so it triggers only for that exact requirement — the
# sibling "authorityCertIssuer/SerialNumber MUST NOT be present" rules constrain
# *content*, hold for self-signed certs too, and are deliberately left untouched.
_AKI_KEYID_SUBJECT = "extensions.authoritykeyidentifier.keyidentifier"


def _is_aki_keyid_presence_rule(ir: Optional[dict]) -> bool:
    if not ir:
        return False
    subject = str(ir.get("subject") or "").lower()
    obligation = str(ir.get("obligation") or "").upper()
    return subject == _AKI_KEYID_SUBJECT and obligation in ("MUST", "SHALL")


def check_applies_expr(section: str, title: str,
                       ir: Optional[dict] = None) -> tuple[str, bool]:
    """Return (go_bool_expr, needs_util) for a lint's CheckApplies guard.

    Section number is the authoritative divisor; the title is a fallback when
    the section is not a recognized §7.1.2.x profile node. Returns ("true",
    False) when the profile is ambiguous — we never broaden, only narrow.

    `ir` (the rule's extracted IR) lets us apply requirement-specific scope
    carve-outs grounded in the obligation itself, e.g. the self-signed exemption
    for an AKI-keyIdentifier presence rule."""
    expr = _section_scope(section)
    if expr is None:
        t = (title or "").lower()
        for needle, pred in _SCOPE_BY_TITLE:
            if needle in t:
                expr = pred
                break
    if expr is None and not _is_aki_keyid_presence_rule(ir):
        return "true", False

    # Requirement-grounded narrowing: exempt self-signed certs from the
    # AKI-keyIdentifier presence obligation (mirrors zlint's own carve-out).
    if _is_aki_keyid_presence_rule(ir):
        base = expr or "true"
        if base == "true":
            return "!util.IsSelfSigned(c)", True
        return f"{base} && !util.IsSelfSigned(c)", True

    return expr, True


def render_intree_file(rule_id: int,
                       source: str,
                       section: str,
                       rule_text: str,
                       tree,
                       precondition=None,
                       severity: str = "lint.Error",
                       title: Optional[str] = None,
                       ir: Optional[dict] = None) -> dict:
    """Render a full in-tree zlint Go file for a generated lint.

    Returns {pkg, lint_name, struct_name, filename, file_content}. Raises
    dsl.DSLError / ValueError if the tree cannot be lowered or the source is
    unsupported. Does NOT touch the filesystem (see write_intree_lint)."""
    pkg, source_const = resolve_package(source)
    out = tree_codegen.render_from_tree(tree, precondition, severity)
    imports = set(out["imports"])

    # Profile-scope guard: narrow CheckApplies to the certificate type the rule
    # is written for. Falls back to "true" when the profile is ambiguous.
    applies_expr, needs_util = check_applies_expr(section, title, ir)
    if needs_util:
        imports.add("github.com/zmap/zlint/v3/util")

    lint_name = lint_name_for(rule_id, tree)
    struct_name = f"CicasGen{int(rule_id)}"
    file_content = _INTREE_FILE_TEMPLATE.format(
        source=source or "", section=section or "", rule_id=int(rule_id),
        pkg=pkg,
        imports=_build_imports(imports),
        name_lit=_go_string(lint_name),
        desc_lit=_go_string(rule_text or ""),
        citation_lit=_go_string(f"{source}: {section}" if section else (source or "")),
        source_const=source_const,
        struct_name=struct_name,
        check_applies_expr=applies_expr,
        execute_body=out["execute_body"],
    )
    # one file per generated lint; the name is unique by rule_id.
    filename = f"lint_{lint_name}.go"
    return {
        "pkg": pkg,
        "lint_name": lint_name,
        "struct_name": struct_name,
        "filename": filename,
        "file_content": file_content,
    }


def write_intree_lint(zlint_v3: Path, rendered: dict) -> Path:
    """Write a rendered in-tree lint file into zlint/v3/lints/<pkg>/. Returns the
    written path. The package dir must already exist (it's an upstream dir)."""
    pkg_dir = Path(zlint_v3) / "lints" / rendered["pkg"]
    if not pkg_dir.is_dir():
        raise FileNotFoundError(f"zlint lints package dir not found: {pkg_dir}")
    out_file = pkg_dir / rendered["filename"]
    out_file.write_text(rendered["file_content"])
    return out_file
