"""templates_v2 / runner.py — full-lint rendering + compile harness.

Given (rule_id, source, section, rule_text, template_id, slots) from
templates_v2.catalog, build a complete zlint v3-compatible Go file and
verify it compiles via `go build` against a scratch module that points
at the local zlint v3 + zcrypto via `replace` directives.

This file is the structural-correctness oracle: anything render_body()
returns from a fill_check'd / dsl.validate'd input MUST compile.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from . import catalog, dsl, render, vocab as V


# ---------------------------------------------------------------------
# Project paths (must match exp_codegen_compile_check.py setup)
# ---------------------------------------------------------------------

ROOT       = Path(__file__).resolve().parent.parent.parent
ZLINT_PATH = Path(os.environ.get(
    "ZLINT_LOCAL",
    "/home/bernhard/projects/cicas/cicas_backend/zlint/v3")).resolve()
MODNAME    = "local/cicas_v2_check"


# ---------------------------------------------------------------------
# Full-file template
# ---------------------------------------------------------------------

_FILE_TEMPLATE = '''\
// Code generated by CICAS rule-codegen — DO NOT EDIT.
// NOT a zlint-authored lint; auto-generated from a spec rule and MUST NOT be
// counted as zlint coverage (generated lint-name prefix: cicasgen_).

package {pkg}

import (
{imports}
)

type {struct_name} struct{{}}

func init() {{
\tlint.RegisterCertificateLint(&lint.CertificateLint{{
\t\tLintMetadata: lint.LintMetadata{{
\t\t\tName:        {name_lit},
\t\t\tDescription: {desc_lit},
\t\t\tCitation:    {citation_lit},
\t\t\tSource:      lint.{source_const},
\t\t}},
\t\tLint: New{struct_name},
\t}})
}}

func New{struct_name}() lint.LintInterface {{
\treturn &{struct_name}{{}}
}}

func (l *{struct_name}) CheckApplies(c *x509.Certificate) bool {{
\treturn true
}}

func (l *{struct_name}) Execute(c *x509.Certificate) *lint.LintResult {{
{execute_body}
}}
'''

# CRL (RevocationList) lint shell — identical structure to _FILE_TEMPLATE but
# registers a RevocationListLint and operates on *x509.RevocationList.
_CRL_FILE_TEMPLATE = '''\
// Code generated by CICAS rule-codegen — DO NOT EDIT.
// NOT a zlint-authored lint; auto-generated from a spec rule and MUST NOT be
// counted as zlint coverage (generated lint-name prefix: cicasgen_).

package {pkg}

import (
{imports}
)

type {struct_name} struct{{}}

func init() {{
\tlint.RegisterRevocationListLint(&lint.RevocationListLint{{
\t\tLintMetadata: lint.LintMetadata{{
\t\t\tName:        {name_lit},
\t\t\tDescription: {desc_lit},
\t\t\tCitation:    {citation_lit},
\t\t\tSource:      lint.{source_const},
\t\t}},
\t\tLint: New{struct_name},
\t}})
}}

func New{struct_name}() lint.RevocationListLintInterface {{
\treturn &{struct_name}{{}}
}}

func (l *{struct_name}) CheckApplies(c *x509.RevocationList) bool {{
\treturn true
}}

func (l *{struct_name}) Execute(c *x509.RevocationList) *lint.LintResult {{
{execute_body}
}}
'''

# Multi-severity branch shell: ONE Go file registers N lints in a single
# init(), each with its own struct, constructor, and Execute body. Used
# for rules with mixed-severity clauses (e.g. orgUnit MUST NOT + commonName
# NOT RECOMMENDED in the same rule). Each branch is an independent zlint
# Lint, but they share the rule_id, Description, Citation, and Source
# metadata so the bundle stays attributable to the single source rule.
_FILE_TEMPLATE_MULTI_HEADER = '''\
// Code generated by CICAS rule-codegen — DO NOT EDIT.
// NOT a zlint-authored lint; auto-generated from a spec rule and MUST NOT be
// counted as zlint coverage (generated lint-name prefix: cicasgen_).

package {pkg}

import (
{imports}
)

func init() {{
{registrations}
}}
'''

_FILE_TEMPLATE_MULTI_REGISTRATION = '''\
\tlint.RegisterCertificateLint(&lint.CertificateLint{{
\t\tLintMetadata: lint.LintMetadata{{
\t\t\tName:        {name_lit},
\t\t\tDescription: {desc_lit},
\t\t\tCitation:    {citation_lit},
\t\t\tSource:      lint.{source_const},
\t\t}},
\t\tLint: New{struct_name},
\t}})'''

_FILE_TEMPLATE_MULTI_BRANCH = '''\

type {struct_name} struct{{}}

func New{struct_name}() lint.LintInterface {{
\treturn &{struct_name}{{}}
}}

func (l *{struct_name}) CheckApplies(c *x509.Certificate) bool {{
\treturn true
}}

func (l *{struct_name}) Execute(c *x509.Certificate) *lint.LintResult {{
{execute_body}
}}
'''


def _sanitize_pkg_name(rule_id, slug: str = "") -> str:
    # Distinct, unmistakable namespace so generated lints are recognizable at a
    # glance and can NEVER be mistaken for / counted as zlint-authored lints.
    # zlint names use e_/w_/n_ severity prefixes; "cicasgen_" deliberately does
    # not, and the coverage matcher + zlint extractor both reject this prefix.
    # When a descriptive slug is available (derived from the DSL tree), the name
    # mimics zlint's readable form — cicasgen_<slug>_<rule_id> — instead of the
    # opaque cicasgen_<rule_id>. The trailing rule_id guarantees uniqueness (the
    # package name doubles as the on-disk directory) without a global registry.
    if slug:
        name = f"cicasgen_{slug}_{int(rule_id)}"
    else:
        name = f"cicasgen_{int(rule_id):04d}"
    name = re.sub(r"[^a-z0-9_]", "_", name.lower())
    return re.sub(r"_+", "_", name).strip("_")


def _struct_name(rule_id) -> str:
    return f"CicasGen{int(rule_id):04d}"


def _tree_slug(tree) -> str:
    """Descriptive snake_case slug for a DSL predicate tree (faithful, no LLM).
    Empty string when no tree is given or the walk fails — callers then fall
    back to the opaque rule_id-only name."""
    if tree is None:
        return ""
    try:
        from .tree_to_natural import tree_slug
        return tree_slug(tree)
    except Exception:
        return ""


def _go_string(s: str) -> str:
    out = '"'
    for ch in s or "":
        if ch == "\\": out += "\\\\"
        elif ch == '"': out += '\\"'
        elif ch == "\n": out += "\\n"
        elif ch == "\r": out += "\\r"
        elif ch == "\t": out += "\\t"
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            out += f"\\u{ord(ch):04x}"
        else:
            out += ch
    out += '"'
    return out


def _source_const(source: str) -> str:
    s = (source or "").upper()
    if "RFC" in s or "5280" in s: return "RFC5280"
    if "CABF" in s or "BR" in s:  return "CABFBaselineRequirements"
    return "Community"


def _build_imports(imps: set) -> str:
    """Sorted, with stdlib block separated from external."""
    stdlib = sorted(i for i in imps if "/" not in i or i.startswith(("math", "regexp", "time", "fmt")))
    external = sorted(i for i in imps if i not in stdlib)
    lines = []
    for i in stdlib:
        lines.append(f'\t"{i}"')
    if external and stdlib:
        lines.append("")
    for i in external:
        lines.append(f'\t"{i}"')
    return "\n".join(lines)


@dataclass
class RenderedLint:
    rule_id: int
    pkg: str
    struct_name: str
    file_content: str
    imports: set
    statement: str
    template_id: str
    slots: dict
    severity: str = "lint.Error"


def render_full_lint_from_tree(rule_id: int,
                               source: str,
                               section: str,
                               rule_text: str,
                               execute_body: str,
                               imports: set,
                               severity: str = "lint.Error",
                               label: str = "",
                               tree=None) -> RenderedLint:
    """Tree-codegen variant of render_full_lint: takes a pre-rendered
    execute_body + imports (from tree_codegen.render_from_tree) and wraps
    them in the standard zlint file shell. No catalog template required.

    `tree` (the DSL predicate) is used only to derive a descriptive lint name
    (cicasgen_<slug>_<rule_id>); pass it when available."""
    pkg = _sanitize_pkg_name(rule_id, _tree_slug(tree))
    struct = _struct_name(rule_id)
    file_content = _FILE_TEMPLATE.format(
        pkg=pkg,
        imports=_build_imports(imports),
        struct_name=struct,
        name_lit=_go_string(pkg),
        desc_lit=_go_string(rule_text or ""),
        citation_lit=_go_string(f"{source}: {section}" if section else (source or "")),
        source_const=_source_const(source),
        execute_body=execute_body,
    )
    return RenderedLint(
        rule_id=int(rule_id), pkg=pkg, struct_name=struct,
        file_content=file_content, imports=imports,
        statement=label or "", template_id="<tree>", slots={},
        severity=severity,
    )


def render_full_crl_lint_from_tree(rule_id: int,
                                   source: str,
                                   section: str,
                                   rule_text: str,
                                   execute_body: str,
                                   imports: set,
                                   severity: str = "lint.Error",
                                   label: str = "",
                                   tree=None) -> RenderedLint:
    """CRL analogue of render_full_lint_from_tree: wraps a pre-rendered
    RevocationList Execute body in the _CRL_FILE_TEMPLATE shell."""
    pkg = _sanitize_pkg_name(rule_id, _tree_slug(tree))
    struct = _struct_name(rule_id)
    file_content = _CRL_FILE_TEMPLATE.format(
        pkg=pkg,
        imports=_build_imports(imports),
        struct_name=struct,
        name_lit=_go_string(pkg),
        desc_lit=_go_string(rule_text or ""),
        citation_lit=_go_string(f"{source}: {section}" if section else (source or "")),
        source_const=_source_const(source),
        execute_body=execute_body,
    )
    return RenderedLint(
        rule_id=int(rule_id), pkg=pkg, struct_name=struct,
        file_content=file_content, imports=imports,
        statement=label or "", template_id="<crl-tree>", slots={},
        severity=severity,
    )


def render_full_lint_multi_branch(rule_id: int,
                                  source: str,
                                  section: str,
                                  rule_text: str,
                                  branches: list,
                                  imports: set,
                                  tree=None) -> RenderedLint:
    """Emit ONE Go file registering N lints from `branches`, each with
    its own severity, struct, and Execute body. Used for rules that
    bundle clauses at different severities (e.g. MUST NOT + NOT
    RECOMMENDED in one source rule).

    branches: list of dicts with keys:
        - label:        str (used as suffix for the registered Lint name)
        - severity:     "lint.Error" | "lint.Warn" | "lint.Notice"
        - execute_body: pre-rendered Go body (from tree_codegen)
        - predicate:    (optional) DSL tree, used to derive the lint name

    Returns a RenderedLint whose file_content has multiple
    RegisterCertificateLint calls in init(), each pointing at a
    distinct branch struct. The `severity` field on the returned
    RenderedLint is the HIGHEST severity among branches (for routing
    purposes).
    """
    if not branches:
        raise ValueError("render_full_lint_multi_branch: empty branches")
    slug = _tree_slug(tree) or _tree_slug(branches[0].get("predicate"))
    pkg = _sanitize_pkg_name(rule_id, slug)
    base_struct = _struct_name(rule_id)

    # Build per-branch artifacts
    regs: list = []
    branch_blocks: list = []
    for i, br in enumerate(branches):
        suffix_label = (br.get("label") or "").strip() or f"b{i}"
        # Lint name + struct name must be Go-unique within the package
        name_suffix = f"{suffix_label}"
        # sanitize: lowercase, only [a-z0-9_]
        import re
        name_suffix = re.sub(r"[^a-z0-9_]", "_", name_suffix.lower())[:40]
        if not name_suffix:
            name_suffix = f"b{i}"
        lint_name = f"{pkg}_{name_suffix}"
        struct_n = f"{base_struct}{i}_{name_suffix}"
        regs.append(_FILE_TEMPLATE_MULTI_REGISTRATION.format(
            name_lit=_go_string(lint_name),
            desc_lit=_go_string(rule_text or ""),
            citation_lit=_go_string(f"{source}: {section}" if section else (source or "")),
            source_const=_source_const(source),
            struct_name=struct_n,
        ))
        branch_blocks.append(_FILE_TEMPLATE_MULTI_BRANCH.format(
            struct_name=struct_n,
            execute_body=br["execute_body"],
        ))

    registrations = "\n".join(regs)
    body_blocks = "\n".join(branch_blocks)
    header = _FILE_TEMPLATE_MULTI_HEADER.format(
        pkg=pkg, imports=_build_imports(imports),
        registrations=registrations,
    )
    file_content = header + body_blocks

    sev_rank = {"lint.Error": 3, "lint.Warn": 2, "lint.Notice": 1}
    top_sev = max((br["severity"] for br in branches),
                  key=lambda s: sev_rank.get(s, 0))

    return RenderedLint(
        rule_id=int(rule_id), pkg=pkg, struct_name=base_struct,
        file_content=file_content, imports=imports,
        statement=" | ".join(b.get("label","") for b in branches),
        template_id="<tree_multi>", slots={},
        severity=top_sev,
    )


def render_full_lint(rule_id: int,
                     source: str,
                     section: str,
                     rule_text: str,
                     template_id: str,
                     slots: dict,
                     requirement_level: str = "") -> RenderedLint:
    if template_id not in catalog.CATALOG_BY_ID:
        raise dsl.DSLError(f"unknown template_id '{template_id}'")
    t = catalog.CATALOG_BY_ID[template_id]
    errs = catalog.fill_check(t, slots)
    if errs:
        raise dsl.DSLError(f"slot fill_check failed: {errs}")
    severity = catalog.severity_for(rule_text=rule_text,
                                    requirement_level=requirement_level)
    out = catalog.render_body(t, slots, severity=severity)
    body = out["execute_body"]
    imps = out["imports"]
    statement = catalog.render_statement(t, slots)

    # template_id is already a readable handle (e.g. "T_ext_non_critical");
    # use it (minus the "T_" prefix) as the descriptive name slug.
    tmpl_slug = re.sub(r"^t_", "", str(template_id).lower())
    pkg = _sanitize_pkg_name(rule_id, tmpl_slug)
    struct = _struct_name(rule_id)
    file_content = _FILE_TEMPLATE.format(
        pkg=pkg,
        imports=_build_imports(imps),
        struct_name=struct,
        name_lit=_go_string(pkg),
        desc_lit=_go_string(rule_text or ""),
        citation_lit=_go_string(f"{source}: {section}" if section else (source or "")),
        source_const=_source_const(source),
        execute_body=body,
    )
    return RenderedLint(
        rule_id=int(rule_id), pkg=pkg, struct_name=struct,
        file_content=file_content, imports=imps,
        statement=statement, template_id=template_id, slots=slots,
        severity=severity,
    )


# ---------------------------------------------------------------------
# Compile harness
# ---------------------------------------------------------------------

GO_MOD = """\
module {mod}

go 1.21

replace github.com/zmap/zlint/v3 => {zlint}
"""


def build_workspace(workspace: Path) -> None:
    """Lay out a scratch Go module that depends on local zlint + zcrypto."""
    (workspace / "pkgs").mkdir(parents=True, exist_ok=True)
    (workspace / "go.mod").write_text(GO_MOD.format(
        mod=MODNAME, zlint=ZLINT_PATH))
    # tiny main so go-tooling doesn't complain
    (workspace / "main.go").write_text(
        "package main\n\nfunc main() {}\n")
    # populate go.sum + transitive deps
    for pkg in ("github.com/zmap/zlint/v3", "github.com/zmap/zcrypto"):
        r = subprocess.run(["go", "get", pkg], cwd=workspace,
                           capture_output=True, timeout=300, text=True)
        if r.returncode != 0:
            raise RuntimeError(f"go get {pkg} failed: {r.stderr[:500]}")


def write_lint(workspace: Path, rl: RenderedLint) -> Path:
    pkg_dir = workspace / "pkgs" / rl.pkg
    pkg_dir.mkdir(parents=True, exist_ok=True)
    out_file = pkg_dir / f"{rl.pkg}.go"
    out_file.write_text(rl.file_content)
    return out_file


def go_build(workspace: Path, rl: RenderedLint, timeout: int = 60) -> tuple:
    """Run `go build ./pkgs/<pkg>` in workspace.
    Returns (ok: bool, stderr: str)."""
    pkg_path = f"./pkgs/{rl.pkg}"
    env = os.environ.copy()
    env.setdefault("GO111MODULE", "on")
    env.setdefault("GOFLAGS", "-mod=mod")
    try:
        proc = subprocess.run(
            ["go", "build", pkg_path],
            cwd=workspace, env=env,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return False, "timeout"
    except FileNotFoundError:
        return False, "go binary not found"
    if proc.returncode == 0:
        return True, ""
    stderr = (proc.stderr or b"").decode("utf-8", errors="replace")
    stdout = (proc.stdout or b"").decode("utf-8", errors="replace")
    return False, (stderr or stdout)[:1500]


def compile_check_one(rl: RenderedLint, workspace: Optional[Path] = None) -> tuple:
    """If workspace is None, create a fresh tempdir. Returns (ok, stderr)."""
    if workspace is None:
        with tempfile.TemporaryDirectory(prefix="cicas_v2_") as tmp:
            ws = Path(tmp)
            build_workspace(ws)
            write_lint(ws, rl)
            return go_build(ws, rl)
    write_lint(workspace, rl)
    return go_build(workspace, rl)


# ---------------------------------------------------------------------
# Self-test: render 5 hand-crafted lints + compile each
# ---------------------------------------------------------------------

if __name__ == "__main__":
    cases = [
        # (rule_id, source, section, rule_text, template_id, slots)
        (3899, "RFC", "4.2.2.1",
         "Conforming CAs MUST mark this extension as non-critical (AIA).",
         "T_ext_non_critical",
         {"OID_CONST": "AiaOID", "FIELD_LABEL": "Authority Information Access"}),

        (4087, "RFC", "4.2.1.6",
         "If the subject field contains an empty sequence, then the issuing CA MUST include a subjectAltName extension that is marked as critical.",
         "T_ext_critical",
         {"OID_CONST": "SubjectAlternateNameOID", "FIELD_LABEL": "subjectAltName"}),

        (4664, "CABF-BR", "12",
         "stateOrProvinceName MUST be present.",
         "T_dn_field_present",
         {"DN_FIELD": "Subject.Province", "FIELD_LABEL": "stateOrProvinceName"}),

        (4566, "CABF-BR", "7.1",
         "TLS Subscriber Certificates MUST contain id-kp-serverAuth in extKeyUsage.",
         "T_eku_required",
         {"BITS": ["ServerAuth"], "FIELD_LABEL": "TLS Subscriber"}),

        (5139, "CABF-BR", "12",
         "organizationalUnitName MUST NOT be included in Root CA Certificates.",
         "T_conditional",
         {"PRECONDITION": {"op": "IsRootCA", "args": []},
          "REQUIREMENT": {"op": "FieldEmpty", "args": ["Subject.OrganizationalUnit"]},
          "PRECONDITION_LABEL": "the certificate is a Root CA",
          "REQUIREMENT_LABEL": "organizationalUnitName MUST NOT be included"}),

        (9999, "RFC", "5280",
         "SerialNumber MUST be in [1, 2^159).",
         "T_field_in_range",
         {"FIELD": "SerialNumber", "LO": 1, "HI": "MAX_INT",
          "FIELD_LABEL": "SerialNumber"}),
    ]

    print(f"zlint: {ZLINT_PATH}  exists={ZLINT_PATH.exists()}")

    with tempfile.TemporaryDirectory(prefix="cicas_v2_test_") as tmp:
        ws = Path(tmp)
        build_workspace(ws)
        print(f"workspace: {ws}\n")
        n_pass = 0; n_fail = 0
        for rid, src, sec, txt, tid, slots in cases:
            print(f"--- R{rid}  template={tid} ---")
            try:
                rl = render_full_lint(rid, src, sec, txt, tid, slots)
            except Exception as e:
                print(f"  RENDER ERROR: {e}\n")
                n_fail += 1; continue
            write_lint(ws, rl)
            ok, err = go_build(ws, rl)
            if ok:
                print(f"  PASS  imports: {sorted(rl.imports)}")
                n_pass += 1
            else:
                print(f"  FAIL  err: {err.strip().splitlines()[0] if err else ''}")
                # dump the file for diagnosis
                print(f"  file: {ws / 'pkgs' / rl.pkg / (rl.pkg + '.go')}")
                n_fail += 1
            print()
        print(f"\nresult: {n_pass} pass / {n_fail} fail / {len(cases)} total")
