"""tree_to_natural.py — mechanical DSL tree → PKI-English summary.

Replaces the LLM-based `exp_goal2_true_verification.extract_one` step
when we already own the DSL tree (i.e. the lint was generated by our
own tree_codegen pipeline). Closes the verification loop with a
deterministic translator instead of round-tripping through an LLM
that has been observed to drop or invert conditional preconditions.

Conditional shape:
  - precondition None         -> "<predicate>"
  - precondition = Not(inner) -> "WHEN <not inner>, THEN <predicate>"
                                 (rule applies when inner is FALSE)
  - precondition = X          -> "WHEN <X>, THEN <predicate>"
                                 (rule applies when X is TRUE)

Atom rendering: each atom has a single natural-language template.
"""
from __future__ import annotations

import re

from . import dsl


# ---------------------------------------------------------------------
# REGEX_SEMANTIC_HINTS — closed mapping from named-regex symbol → human
# readable semantic description. The judge sees the regex by NAME only,
# so opaque symbols like 'Re_LDH_Hostname' force the judge to guess what
# the pattern actually enforces. This dict makes the regex's enforced
# property explicit in the extracted PKI-English sentence, mirroring the
# binary_judge.py REGEX-BASED LIST PREDICATES guidance.
#
# Keys MUST match entries in vocab.NAMED_REGEXES. Values are short PKI
# phrases describing the property the regex enforces, NOT the pattern
# itself.
# ---------------------------------------------------------------------
REGEX_SEMANTIC_HINTS: dict[str, str] = {
    "Re_LDH_Hostname":
        "is an LDH-labeled hostname with at least one dot (FQDN multi-label structure: per-label LDH compliance AND ≥2 labels)",
    "Re_LDH_Label":
        "is a single valid LDH label (no FQDN structure required)",
    "Re_ReservedLDH_Excluded":
        "is an LDH label that is NOT in the IANA-reserved LDH label set",
    "Re_HttpOrLdapStrict":
        "is a URI with scheme http:// or ldap:// (strict, excluding https/ldaps)",
    "Re_HttpOrLdapUrl":
        "is a URI with scheme http://, https://, ldap://, or ldaps:// (lenient)",
    "Re_Rfc3986Uri":
        "is a valid RFC 3986 URI (scheme + optional authority/path/query/fragment, no whitespace)",
    "Re_NoAtSign":
        "does not contain the '@' character",
    "Re_NoUnderscore":
        "does not contain the '_' character",
    "Re_NoConsecutiveDots":
        "does not contain consecutive '..' (no empty DNS labels)",
    "Re_AnyUri":
        "begins with a valid URI scheme",
    "Re_TorV3Onion":
        "is a valid Tor v3 onion service address (.onion with 56-char base32)",
    "Re_SerialNumberString":
        "is a valid positive decimal integer (serial number string format, per RFC 5280)",
    "Re_FQDN_AtLeastTwoLabels":
        "is an LDH-labeled hostname with at least one dot (FQDN multi-label structure: per-label LDH compliance AND ≥2 labels)",
}


# ---------------------------------------------------------------------
# FIELD_VALUE_HINTS — closed mapping (field_name, value) → human readable
# PKI phrase. Some library-parsed fields use integer/enum values that
# differ from the rule-text mention (e.g. zcrypto `Version` field holds
# the human-readable X.509 version number 1/2/3, while RFC/CABF rules
# may quote the on-the-wire DER INTEGER value 0/1/2). The judge sees
# only the literal `FieldEq(Version, 2)` rendering and may guess wrong.
# This dict makes the field-value semantic explicit.
#
# Keys: (field_name, value-as-string) tuples. Values: PKI phrase.
# ---------------------------------------------------------------------
FIELD_VALUE_HINTS: dict[tuple, str] = {
    ("Version", "1"): "the certificate is X.509 version 1 (v1; zcrypto Version field value 1)",
    ("Version", "2"): "the certificate is X.509 version 2 (v2; zcrypto Version field value 2; on-the-wire DER INTEGER value is 1)",
    ("Version", "3"): "the certificate is X.509 version 3 (v3; zcrypto Version field value 3; on-the-wire DER INTEGER value is 2)",
}


def _field_value_phrase(field: str, value) -> str:
    """Map a (field, value) pair to a PKI-English phrase if a hint exists."""
    hint = FIELD_VALUE_HINTS.get((field, str(value)))
    if hint:
        return hint
    return f"field {field} equals {value!r}"


def _regex_phrase(name: str) -> str:
    """Map a named-regex symbol to a PKI-English phrase ('matches X')."""
    hint = REGEX_SEMANTIC_HINTS.get(name)
    if hint:
        return hint
    return f"matches regex {name}"


# ---------------------------------------------------------------------
# atom -> phrase
# ---------------------------------------------------------------------
# Friendly names for OID consts whose bare identifier the synonymy judge would
# not connect to the rule's category term (e.g. the const "OidPolicyDomainValidated"
# IS one of CABF's "Reserved Certificate Policy Identifiers"). Naming the standard
# set semantically lets the judge recognise it — accurate, not leading.
_OID_FRIENDLY = {
    "OidPolicyDomainValidated":       "the CABF domain-validated Reserved Certificate Policy Identifier (2.23.140.1.2.1)",
    "OidPolicyOrganizationValidated": "the CABF organization-validated Reserved Certificate Policy Identifier (2.23.140.1.2.2)",
    "OidPolicyIndividualValidated":   "the CABF individual-validated Reserved Certificate Policy Identifier (2.23.140.1.2.3)",
    "OidPolicyExtendedValidation":    "the CABF extended-validation Reserved Certificate Policy Identifier (2.23.140.1.1)",
    "AnyPolicyOID":                   "the anyPolicy OID (2.5.29.32.0)",
}


def _oid_name(o) -> str:
    return _OID_FRIENDLY.get(o, str(o))


def _atom(n) -> str:
    if isinstance(n, dsl.ExtPresent):
        return f"the extension with OID {n.oid} is present"
    if isinstance(n, dsl.ExtCritical):
        return f"the extension with OID {n.oid} is marked critical"
    if isinstance(n, dsl.ExtNotCritical):
        return f"the extension with OID {n.oid} is marked non-critical"
    if isinstance(n, dsl.ExtContentNonEmpty):
        # "MUST contain at least one X" — the extension's parsed content has >=1 element.
        # Sound only where zcrypto exposes the extension's content (nameConstraints subtree
        # lists; the renderer refuses others). Describes the semantic property.
        return (f"the extension with OID {n.oid} carries a non-empty content SEQUENCE "
                f"(at least one sub-element is present)")
    if isinstance(n, dsl.IsCA):
        return "the certificate is a CA certificate"
    if isinstance(n, dsl.IsRootCA):
        return "the certificate is a Root CA certificate"
    if isinstance(n, dsl.IsSubCA):
        return "the certificate is a Subordinate CA certificate"
    if isinstance(n, dsl.PathLenConstraintPresent):
        return "the basicConstraints extension carries a pathLenConstraint field (it is present)"
    if isinstance(n, dsl.IsServerCert):
        return "the certificate is a TLS server certificate"
    if isinstance(n, dsl.IsSubscriberCert):
        return "the certificate is a Subscriber certificate"
    if isinstance(n, dsl.SigAlgMatchesTBSSignature):
        return ("the certificate's signatureAlgorithm field is byte-for-byte "
                "identical to the tbsCertificate.signature field")
    if isinstance(n, dsl.CommonNameFromSAN):
        return ("the subject commonName, if present, equals one of the "
                "subjectAltName dNSName or iPAddress entries")
    if isinstance(n, dsl.NotAfterIsNoExpirySentinel):
        return ("the notAfter date is the GeneralizedTime no-expiration sentinel "
                "99991231235959Z (RFC 5280 §4.1.2.5)")
    if isinstance(n, dsl.KeyUsageHas):
        return f"the KeyUsage extension asserts the {n.bit} bit"
    if isinstance(n, dsl.ExtKeyUsageHas):
        return f"the ExtendedKeyUsage extension asserts the {n.bit} usage"
    if isinstance(n, dsl.FieldEq):
        return _field_value_phrase(n.field, n.value)
    if isinstance(n, dsl.FieldNonEmpty):
        return f"field {n.field} is non-empty (present)"
    if isinstance(n, dsl.FieldEmpty):
        return f"field {n.field} is empty (absent)"
    if isinstance(n, dsl.FieldMatchesRegex):
        return f"field {n.field} {_regex_phrase(n.pattern)}"
    if isinstance(n, dsl.FieldNotMatchesRegex):
        return f"field {n.field} does NOT satisfy ({_regex_phrase(n.pattern)})"
    if isinstance(n, dsl.FieldInSet):
        return f"field {n.field} is one of {list(n.values)}"
    if isinstance(n, dsl.FieldNotInSet):
        return f"field {n.field} is NOT one of {list(n.values)}"
    if isinstance(n, dsl.FieldLenInRange):
        # lo==0 is the trivial floor (a length is always >= 0), so the operative
        # constraint is the upper bound alone. Render "at most hi" rather than the
        # spurious two-sided range [0, hi] — faithful (for a length, [0, hi] is
        # logically identical to "<= hi") and mirrors the FieldCount renderer below.
        if n.lo in (0, None):
            return f"length of {n.field} is at most {n.hi} octet(s)"
        return f"length of {n.field} is in range [{n.lo}, {n.hi}]"
    if isinstance(n, dsl.FieldNumericInRange):
        # An open upper bound (MAX_INT) is NOT a real constraint — the Go emitter
        # renders it as `&& true`. Phrase it as an open-ended lower bound so the
        # synonymy judge does not read "[0, MAX_INT]" as an invented implementation
        # ceiling (e.g. "serialNumber MUST be a non-negative integer").
        if n.hi == "MAX_INT" or n.hi is None:
            if n.lo == 0:
                return f"numeric value of {n.field} is non-negative (>= 0, no upper bound)"
            return f"numeric value of {n.field} is at least {n.lo} (no upper bound)"
        if n.lo == n.hi:
            return f"numeric value of {n.field} equals {n.lo}"
        return f"numeric value of {n.field} is in range [{n.lo}, {n.hi}]"
    if isinstance(n, dsl.FieldCount):
        hi = n.hi
        if n.field == "ExtKeyUsage":
            if hi == "MAX_INT" or hi is None:
                return f"the ExtendedKeyUsage extension contains at least {n.lo} KeyPurposeId value(s)"
            if n.lo == hi:
                return f"the ExtendedKeyUsage extension contains exactly {n.lo} KeyPurposeId value(s)"
            return f"the ExtendedKeyUsage extension contains between {n.lo} and {hi} KeyPurposeId value(s)"
        if hi == "MAX_INT" or hi is None:
            return f"field {n.field} occurs at least {n.lo} time(s)"
        if n.lo == 0:
            return f"field {n.field} occurs at most {hi} time(s)"
        if n.lo == hi:
            return f"field {n.field} occurs exactly {n.lo} time(s)"
        return f"field {n.field} occurs between {n.lo} and {hi} time(s)"
    if isinstance(n, dsl.FieldEncodedAs):
        opts = " or ".join(n.types)
        # For whole-DN holders (Subject/Issuer) the generated code walks the
        # RDNSequence DER and checks the tag of EVERY attribute value (see
        # render._emit_dn_values_encoded_as) — render σ to match that real
        # behavior rather than implying a single field-level tag.
        if n.field in ("Subject", "Issuer"):
            return (f"every attribute value in the {n.field} DN is "
                    f"ASN.1-encoded as {opts}")
        return f"field {n.field} is ASN.1-encoded as {opts}"
    if isinstance(n, dsl.DNDirectoryStringValuesEncodedAs):
        opts = " or ".join(n.types)
        return (f"every DirectoryString-type attribute value in the {n.dn} DN is "
                f"ASN.1-encoded as {opts} (non-DirectoryString attributes such as "
                f"countryName / domainComponent are exempt)")
    if isinstance(n, dsl.FieldContains):
        return f"field {n.field} contains the substring {n.substring!r}"
    if isinstance(n, dsl.CrossFieldEq):
        return f"field {n.field_a} equals field {n.field_b}"
    if isinstance(n, dsl.DateAfter):
        return f"{n.later} is after {n.earlier}"
    if isinstance(n, dsl.DateBefore):
        return f"{n.earlier} is before {n.later}"
    if isinstance(n, dsl.ListAllMatch):
        return f"every entry in {n.list_field} satisfies ({_render(n.predicate)})"
    if isinstance(n, dsl.ListAnyMatch):
        return f"at least one entry in {n.list_field} satisfies ({_render(n.predicate)})"
    if isinstance(n, dsl.ListUnique):
        return f"all entries in {n.list_field} are pairwise distinct"
    if isinstance(n, dsl.WildcardFilter):
        return (f"every entry in {n.list_field} that begins with prefix {n.prefix!r} "
                f"satisfies ({_render(n.predicate)})")
    if isinstance(n, dsl.ItemMatchesRegex):
        return f"the iteration item {_regex_phrase(n.pattern)}"
    if isinstance(n, dsl.ItemNotMatchesRegex):
        return f"the iteration item does NOT satisfy ({_regex_phrase(n.pattern)})"
    if isinstance(n, dsl.ItemInSet):
        return f"the iteration item is one of {list(n.values)}"
    if isinstance(n, dsl.ItemEq):
        return f"the iteration item equals {n.value!r}"
    if isinstance(n, dsl.ItemLenIn):
        return f"length of the iteration item is in {list(n.counts)}"
    if isinstance(n, dsl.BytesEq):
        return f"raw bytes of {n.field_a} equal raw bytes of {n.field_b}"
    if isinstance(n, dsl.BytesEqualsHex):
        return f"raw bytes of {n.field} equal hex {n.hex_lit}"
    if isinstance(n, dsl.BytesContainsHex):
        return f"raw bytes of {n.field} contain hex {n.hex_lit}"
    if isinstance(n, dsl.BytesContainsOidDer):
        return f"raw bytes of {n.field} contain the DER encoding of OID {n.oid}"
    if isinstance(n, dsl.IPListAllOctetCount):
        return f"every IP in {n.field} has {n.count} octets"
    if isinstance(n, dsl.IPListAllOctetCountIn):
        return f"every IP in {n.field} has octet count in {list(n.counts)}"
    if isinstance(n, dsl.OidListContains):
        return f"OID list {n.field} contains {_oid_name(n.oid)}"
    if isinstance(n, dsl.OidListCountInSet):
        names = " or ".join(_oid_name(o) for o in n.allowed_oids)
        hi = "unbounded" if n.hi == "MAX_INT" else n.hi
        rng = f"exactly {n.lo}" if n.lo == n.hi else f"between {n.lo} and {hi}"
        return (f"the number of entries in {n.field} that are "
                f"{names} is {rng}")
    if isinstance(n, dsl.PublicKeyAlgorithmIs):
        return f"the SubjectPublicKey algorithm is {n.algorithm}"
    if isinstance(n, dsl.DNEmpty):
        return f"the {n.holder} DN is the empty SEQUENCE"
    if isinstance(n, dsl.RDNCountInRange):
        return f"the {n.holder} DN contains between {n.lo} and {n.hi} RDNs"
    if isinstance(n, dsl.RDNHasSingleAttribute):
        return f"each RDN in the {n.holder} DN carries exactly one attribute-value pair"
    if isinstance(n, dsl.RDNSequenceHasCountryBefore):
        return f"if both countryName and stateOrProvinceName appear in the {n.holder} DN, countryName precedes stateOrProvinceName"
    if isinstance(n, dsl.ExtRawValueEqualsHex):
        return (f"the extension with OID {n.oid} is present "
                f"AND its raw extnValue equals hex {n.hex_lit}")
    if isinstance(n, dsl.ExtRawValueContainsHex):
        return (f"the extension with OID {n.oid} is present "
                f"AND its raw extnValue contains hex {n.hex_lit}")
    if isinstance(n, dsl.ExtSubfieldPresent):
        sub = n.subfield or f"the [{n.tag}] context-tagged sub-element"
        if n.path == "generalsubtree":
            return (f"at least one GeneralSubtree inside the {n.oid} extension "
                    f"carries the {sub} field (ASN.1 context tag [{n.tag}])")
        return (f"the {n.oid} extension is present AND its {sub} sub-field "
                f"(ASN.1 context tag [{n.tag}]) is present in the encoded extension")
    if isinstance(n, dsl.OidEq):
        return f"OID field {n.field} equals OID constant {n.oid}"
    if isinstance(n, dsl.SubtreeIPListAnyHasOctetCount):
        kind = {8: "IPv4 (4-octet IP + 4-octet mask)",
                32: "IPv6 (16-octet IP + 16-octet mask)"}.get(n.count, f"{n.count}-octet")
        return (f"at least one entry in {n.field} has IP+Mask total of "
                f"{n.count} octets ({kind})")
    if isinstance(n, dsl.SubtreeIPListAnyAllZero):
        kind = {8: "IPv4 0.0.0.0/0 marker",
                32: "IPv6 ::0/0 marker"}.get(n.count, f"{n.count}-octet all-zero")
        return (f"at least one entry in {n.field} has IP+Mask total of "
                f"{n.count} octets AND every byte is zero "
                f"(the {kind})")
    if isinstance(n, dsl.SubtreeIPListAnyHasOctetCountAndNotAllZero):
        kind = {8: "real IPv4 entry",
                32: "real IPv6 entry"}.get(n.count, f"{n.count}-octet entry")
        return (f"at least one entry in {n.field} has IP+Mask total of "
                f"{n.count} octets AND has at least one non-zero byte "
                f"(a {kind} that is not the all-zero marker)")
    if isinstance(n, dsl.SubtreeStringListAllMatch):
        return (f"every entry in subtree string list {n.field} satisfies "
                f"({_render(n.predicate)})")
    if isinstance(n, dsl.SubtreeStringListAnyMatch):
        return (f"at least one entry in subtree string list {n.field} satisfies "
                f"({_render(n.predicate)})")
    if isinstance(n, dsl.SubtreeStringListAllMatchOrEmpty):
        return (f"subtree string list {n.field} is empty OR every entry in it "
                f"satisfies ({_render(n.predicate)})")
    if isinstance(n, dsl.SubtreeIPListAllOctetCountIn):
        return (f"every entry in subtree IP list {n.field} has IP+Mask "
                f"total octet count in {list(n.counts)}")
    if isinstance(n, dsl.SubtreeIPMaskValidCIDR):
        return (f"every entry in subtree IP list {n.field} has its mask "
                f"in valid CIDR form (contiguous high-order 1-bits followed "
                f"by zeros, per RFC 4632)")
    if isinstance(n, dsl.ScalarInList):
        return f"scalar field {n.scalar_field} appears in list field {n.list_field}"
    if isinstance(n, dsl.ScalarInAnyOfLists):
        lists = ", ".join(n.list_fields)
        return (f"scalar field {n.scalar_field} appears in at least one of the "
                f"list fields [{lists}]")
    if isinstance(n, dsl.IPv4Conditional):
        return (f"for each IP in {n.field}: if IPv4 then "
                f"({_render(n.ipv4_predicate)}); if IPv6 then "
                f"({_render(n.ipv6_predicate)})")
    if isinstance(n, dsl.SubtreeIPv4Conditional):
        return (f"for each subtree entry in {n.field}: if IPv4 subtree "
                f"(IP part is 4 bytes) then ({_render(n.ipv4_predicate)}); "
                f"if IPv6 subtree (IP part is 16 bytes) then "
                f"({_render(n.ipv6_predicate)}); item byte-length means "
                f"total of IP+Mask")
    if isinstance(n, dsl.ExtHasGeneralNameWithTag):
        # RFC 5280 §4.2.1.6 GeneralName CHOICE tags.
        tagname = {0:"otherName", 1:"rfc822Name", 2:"dNSName", 3:"x400Address",
                   4:"directoryName", 5:"ediPartyName",
                   6:"uniformResourceIdentifier", 7:"iPAddress",
                   8:"registeredID"}.get(n.tag, f"tag {n.tag}")
        # The atom is an IA5 encoding check, NOT a presence check (it is
        # vacuously true when there are zero matching entries). Phrase it
        # so the judge cannot misread it as presence.
        return (f"every {tagname} GeneralName entry in the extension {n.oid} "
                f"is encoded as IA5String (vacuously true when no {tagname} "
                f"entry is present)")
    if isinstance(n, dsl.ExtensionURISchemeNotInSet):
        schemes_str = ", ".join(f"{s!r}" for s in n.schemes)
        return (f"no extension contains a URI whose scheme is one of [{schemes_str}] "
                f"(SHOULD NOT include {schemes_str} URIs in extensions)")
    if isinstance(n, dsl.ExtHasAnyGeneralNameOfTag):
        tagname = {0:"otherName", 1:"rfc822Name", 2:"dNSName", 3:"x400Address",
                   4:"directoryName", 5:"ediPartyName",
                   6:"uniformResourceIdentifier", 7:"iPAddress",
                   8:"registeredID"}.get(n.tag, f"tag {n.tag}")
        return (f"the extension {n.oid} contains at least one GeneralName "
                f"entry of CHOICE type {tagname}")
    if isinstance(n, dsl.DomainComponentOrdered):
        return ("Subject DN's domainComponent fields appear as a single "
                "contiguous ordered sequence")
    if isinstance(n, dsl.AIAHasMethodOtherThan):
        oids = ", ".join(n.allowed_oids)
        return (f"the extension {n.ext_oid} contains at least one "
                f"AccessDescription whose accessMethod is NOT in [{oids}]")
    if isinstance(n, dsl.AIAMethodLocationsTagInSet):
        tags = ", ".join(str(t) for t in n.allowed_tags)
        tagnames = {1:"rfc822Name", 2:"dNSName", 4:"directoryName",
                    6:"uniformResourceIdentifier", 7:"iPAddress", 8:"registeredID"}
        named = ", ".join(tagnames.get(t, str(t)) for t in n.allowed_tags)
        return (f"every AccessDescription in extension {n.ext_oid} whose "
                f"accessMethod is {n.method_oid} has a GeneralName tag in "
                f"[{named}]")
    if isinstance(n, dsl.AIAMethodLocationsAnyMatchRegex):
        hint = REGEX_SEMANTIC_HINTS.get(n.pattern, n.pattern)
        return (f"at least one AccessDescription in extension {n.ext_oid} "
                f"whose accessMethod is {n.method_oid} is a URI that {hint}")
    if isinstance(n, dsl.CRLDPHasNameRelative):
        return ("the CRL Distribution Points extension contains at least one "
                "DistributionPoint using nameRelativeToCRLIssuer (not fullName)")
    if isinstance(n, dsl.CRLDPHasNameRelativeWithMultiIssuer):
        return ("the CRL Distribution Points extension contains at least one "
                "DistributionPoint using nameRelativeToCRLIssuer AND whose "
                "cRLIssuer field has more than one GeneralName")
    if isinstance(n, dsl.ValidityDateAsn1TagInSet):
        tags = ", ".join(n.allowed_tags)
        return (f"the ASN.1 encoding tag of validity date {n.date_field} "
                f"(in the raw TBSCertificate) is one of [{tags}]")
    if isinstance(n, dsl.CertPolicyExplicitTextHasEncodingTagInSet):
        tags = ", ".join(str(t) for t in n.allowed_tags)
        return (f"the CertificatePolicies extension contains at least one "
                f"UserNotice explicitText whose DisplayText CHOICE tag is "
                f"one of [{tags}]")
    if isinstance(n, dsl.PolicyQualifierOIDInSet):
        oid_name = n.oid_const
        return (f"the CertificatePolicies extension contains a policy qualifier "
                f"with OID {oid_name}")
    if isinstance(n, dsl.PolicyQualifierOIDNotInSet):
        oid_name = n.oid_const
        return (f"the CertificatePolicies extension contains no policy qualifier "
                f"with OID {oid_name}")
    if isinstance(n, dsl.AlgorithmIdentifierBytesMatch):
        if n.neg:
            return f"the algorithm identifier is NOT {n.oid_const}"
        return f"the algorithm identifier is {n.oid_const}"
    # ---- SerialNumber constraints (RFC 5280 §4.1.2.4) ----
    if isinstance(n, dsl.SerialNumberPositive):
        return "the certificate serial number is a positive integer (greater than zero)"
    if isinstance(n, dsl.SerialNumberOctetLengthInRange):
        return (f"the certificate serial number has a byte length in the range "
                f"[{n.lo}, {n.hi}]")
    raise dsl.DSLError(f"tree_to_natural: unhandled atom type {type(n).__name__}")


def _render(n) -> str:
    if isinstance(n, dsl.Not):
        return f"NOT ({_render(n.inner)})"
    if isinstance(n, dsl.And):
        return " AND ".join(f"({_render(p)})" for p in n.parts)
    if isinstance(n, dsl.Or):
        return " OR ".join(f"({_render(p)})" for p in n.parts)
    if isinstance(n, dsl.When):
        # conditional node nested inside the tree (vs the top-level precondition
        # param): "WHEN <cond>, THEN <main>", inverting Not(cond) for readability
        # so the judge sees the rule-applies condition literally (no NA-inversion).
        if isinstance(n.cond, dsl.Not):
            return f"WHEN NOT ({_render(n.cond.inner)}), THEN ({_render(n.main)})"
        return f"WHEN ({_render(n.cond)}), THEN ({_render(n.main)})"
    return _atom(n)


# ---------------------------------------------------------------------
# top-level: tree -> sentence
# ---------------------------------------------------------------------
def tree_to_natural(predicate, precondition=None) -> str:
    """Mechanically render a (precondition?, predicate) pair as a PKI-English
    sentence. Mirrors the verifier's expectation:
      - no precondition: '<predicate-phrase>'
      - precondition Not(X): 'WHEN NOT (X), THEN <predicate-phrase>'
      - precondition X: 'WHEN X, THEN <predicate-phrase>'
    The rule-applies condition is the literal precondition tree (if any),
    so the reader does not have to invert anything.
    """
    pred_text = _render(predicate)
    if precondition is None:
        return pred_text
    if isinstance(precondition, dsl.Not):
        cond_text = _render(precondition.inner)
        return f"WHEN NOT ({cond_text}), THEN {pred_text}"
    cond_text = _render(precondition)
    return f"WHEN ({cond_text}), THEN {pred_text}"


# Map RFC2119 obligation level -> generated-lint severity. A lint that returns
# this severity on violation EXPRESSES a rule at that obligation level (see
# binary_judge SEVERITY EQUIVALENCE). MUST/MUST NOT -> Error; SHOULD-family ->
# Warn; MAY/OPTIONAL -> Notice.
_OBLIGATION_SEVERITY = {
    "MUST": "Error", "MUST NOT": "Error", "SHALL": "Error", "SHALL NOT": "Error",
    "REQUIRED": "Error",
    "SHOULD": "Warn", "SHOULD NOT": "Warn",
    "RECOMMENDED": "Warn", "NOT RECOMMENDED": "Warn",
    "MAY": "Notice", "OPTIONAL": "Notice",
}


def obligation_aware_summary(predicate, precondition=None,
                             obligation: str | None = None) -> str:
    """σ_mech for the synonymy judge, carrying the rule's obligation level.

    The bare tree_to_natural() renders a predicate as an unconditional assertion,
    which reads like a MUST even when the rule is SHOULD / NOT RECOMMENDED — the
    judge then (correctly) rejects it as not synonymous, because a hard check does
    NOT express a soft recommendation. A generated lint encodes obligation level
    via its returned SEVERITY (lint.Error / lint.Warn / lint.Notice), not via the
    predicate tree. This wrapper makes that severity explicit so the judge compares
    like with like. MUST-family is rendered bare (the default, severity Error is the
    judge's baseline assumption); SHOULD/MAY families get an explicit severity clause.
    """
    base = tree_to_natural(predicate, precondition)
    sev = _OBLIGATION_SEVERITY.get((obligation or "").strip().upper())
    if sev is None or sev == "Error":
        return base
    return (f"The generated lint returns lint.{sev} (a {obligation}-level finding, "
            f"not a hard error) when violated; it verifies that: {base}")


def tree_branches_to_natural(branches: list) -> str:
    """Render N severity-tagged branches as ONE multi-clause PKI sentence.
    Each branch dict has keys: severity (str), label (str), predicate (DSL),
    optional precondition (DSL).

    Output shape (one line per branch):
      [Clause severity=<S> label=<L>] code returns lint.<S> on violation;
        verifies that <PKI-English sentence>
    The "verifies that" phrasing makes explicit that the predicate is the
    OK condition (Pass) and the severity fires when the predicate is
    FALSE — mirroring binary_judge.py SEVERITY EQUIVALENCE: a code that
    returns lint.<S> on violation EXPRESSES a rule clause at level <S>.
    """
    lines: list = []
    for br in branches:
        sev = br.get("severity", "lint.Error")
        sev_short = {"lint.Error": "Error", "lint.Warn": "Warn",
                     "lint.Notice": "Notice"}.get(sev, sev)
        sev_level = {"lint.Error": "MUST/MUST NOT",
                     "lint.Warn":  "SHOULD/SHOULD NOT/RECOMMENDED/NOT RECOMMENDED",
                     "lint.Notice":"MAY/OPTIONAL"}.get(sev, "")
        label = br.get("label", "")
        sent = tree_to_natural(br["predicate"], br.get("precondition"))
        lines.append(
            f"[Clause severity={sev_short} ({sev_level}) label={label}]: "
            f"code returns lint.{sev_short} on violation; "
            f"verifies (i.e. the OK / lint.Pass condition is) that {sent}"
        )
    return "\n".join(lines)


# ---------------------------------------------------------------------
# tree -> compact descriptive slug (for zlint-style generated lint names)
# ---------------------------------------------------------------------
# A faithful, DETERMINISTIC snake_case summary of a DSL tree, used to name
# generated lints `cicasgen_<slug>_<rule_id>` instead of the opaque
# `cicasgen_<rule_id>`. Mechanical (no LLM, no per-rule table): the verb comes
# from the atom class, the subject from its primary field/oid/bit attribute.

# Short, readable verb per atom class. Anything not listed falls back to a
# snake_cased class name, so new atoms still get a sensible (if longer) slug.
_SLUG_VERB: dict[str, str] = {
    "IsCA": "is_ca", "IsRootCA": "root_ca", "IsSubCA": "sub_ca", "IsServerCert": "server_cert",
    "IsSubscriberCert": "subscriber_cert", "IsEndEntity": "end_entity",
    "ExtPresent": "present", "ExtCritical": "critical", "ExtNotCritical": "not_critical",
    "ExtContentNonEmpty": "content_non_empty",
    "KeyUsageHas": "ku_has", "ExtKeyUsageHas": "eku_has",
    "FieldEq": "eq", "FieldNonEmpty": "present", "FieldEmpty": "absent",
    "FieldInSet": "in_set", "FieldNotInSet": "not_in_set",
    "FieldLenInRange": "len", "FieldNumericInRange": "value",
    "FieldEncodedAs": "encoded_as", "FieldCount": "count",
    "FieldMatchesRegex": "matches", "FieldNotMatchesRegex": "not_matches",
    "FieldContains": "contains",
    "OidListContains": "list_contains", "IPListAllOctetCount": "ip_octets",
    "RSAModulusBitsInRange": "rsa_modulus_bits", "RSAPublicExponentInRange": "rsa_exponent",
    "PublicKeyAlgorithmIs": "pubkey_alg", "DNEmpty": "dn_empty",
}
# Attribute that names the SUBJECT of the atom, in priority order.
_SLUG_KEY_ATTRS = ("oid", "bit", "field", "scalar_field", "list_field",
                   "algorithm", "holder", "value", "pattern", "date_field")
# Atoms whose subject reads better BEFORE the verb (e.g. "aia_not_critical",
# "serial_number_value") rather than after ("eku_has_server_auth").
_SLUG_SUBJECT_FIRST = {
    "ExtPresent", "ExtCritical", "ExtNotCritical",
    "FieldEq", "FieldNonEmpty", "FieldEmpty", "FieldInSet", "FieldNotInSet",
    "FieldLenInRange", "FieldNumericInRange", "FieldEncodedAs", "FieldCount",
    "FieldMatchesRegex", "FieldNotMatchesRegex", "FieldContains",
    "OidListContains", "IPListAllOctetCount",
}


def _slug_token(s) -> str:
    """Normalize one identifier to snake_case ascii: CamelCase/dotted -> snake,
    strip a trailing 'OID' (AiaOID -> aia), drop non-[a-z0-9]."""
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", str(s))
    s = s.replace(".", "_").lower()
    s = re.sub(r"_?oid$", "", s)
    s = re.sub(r"[^a-z0-9]+", "_", s).strip("_")
    return s


def _atom_slug(n) -> str:
    cn = type(n).__name__
    verb = _SLUG_VERB.get(cn) or _slug_token(cn)
    key = None
    for a in _SLUG_KEY_ATTRS:
        v = getattr(n, a, None)
        if isinstance(v, (list, tuple)):
            v = v[0] if v else None
        if v not in (None, ""):
            key = _slug_token(v)
            if key:
                break
    if not key:
        return verb
    return f"{key}_{verb}" if cn in _SLUG_SUBJECT_FIRST else f"{verb}_{key}"


def _walk_slug(n, depth: int = 0) -> str:
    cn = type(n).__name__
    if cn == "Not":
        return "not_" + _walk_slug(n.inner, depth + 1)
    if cn == "When":
        return f"when_{_walk_slug(n.cond, depth + 1)}_{_walk_slug(n.main, depth + 1)}"
    if cn in ("And", "Or"):
        sep = "_and_" if cn == "And" else "_or_"
        kids = [k for k in (_walk_slug(p, depth + 1) for p in n.parts) if k]
        if depth > 0 and len(kids) > 2:        # cap nested fan-out
            kids = kids[:2]
        return sep.join(kids) if kids else _slug_token(cn)
    return _atom_slug(n)


def tree_slug(tree, maxlen: int = 56) -> str:
    """Compact, faithful, deterministic snake_case slug describing a DSL tree,
    for zlint-style generated lint names. Returns 'rule' if the tree can't be
    walked (never raises). Truncates on a word boundary."""
    try:
        s = _walk_slug(tree)
    except Exception:
        s = ""
    s = re.sub(r"_+", "_", s or "").strip("_")
    if len(s) > maxlen:
        s = s[:maxlen].rsplit("_", 1)[0].strip("_") or s[:maxlen].strip("_")
    return s or "rule"


if __name__ == "__main__":
    # smoke test: R4633 expected output
    pred = dsl.parse({"op":"SubtreeIPListAnyAllZero",
                       "args":["PermittedIPAddresses",32]})
    pre = dsl.parse({"op":"Not","args":[
              {"op":"SubtreeIPListAnyHasOctetCountAndNotAllZero",
               "args":["PermittedIPAddresses",32]}]})
    print("R4633:")
    print(" ", tree_to_natural(pred, pre))
    print()
    print("R3910:")
    pred2 = dsl.parse({"op":"And","args":[
        {"op":"ExtPresent","args":["AuthkeyOID"]},
        {"op":"FieldNonEmpty","args":["AuthorityKeyId"]},
    ]})
    print(" ", tree_to_natural(pred2, None))
